### ISSUE TITLE
Setup a pricing page

### ISSUE THREAD

**Issue by nermalcat69** [zeropsio/docs#77]
### Preliminary Checks

- [X] I have searched for similar issues: https://github.com/zeropsio/docs/issues

### Issue Summary

We need a pricing page which covers all the info about our resources and costs.

### Suggested Solution

1.
2.
3.

### Would you like to help fix this issue?

- [ ] I would like to work on this

**Comment by advtszn** [comment]
can i work on this?
also will you be providing the info and design for the page?

**Comment by nermalcat69** [comment]
🤔 i can provide you the info but not sure where to put the pricing page- any idea where we can have the pricing page in our docs ? @777advait 😃

**Comment by advtszn** [comment]
after introduction and before getting started maybe?

**Comment by nermalcat69** [comment]
@dinxsh what do you think?

**Comment by dinxsh** [comment]
preferably last but anywhere should be appropriate i think 😸

**Comment by nermalcat69** [comment]
<img width="395" alt="image" src="https://github.com/user-attachments/assets/d8b8b18d-2ffa-42d4-937b-c4daae45f7f0">

@777advait You can use this section, and feel free to get inspiration from other docs where they have pricing. You can create new components using React in apps/docs/src/components/~ if you'd like. I'll review the PR whenever you open one :)
