### ISSUE TITLE
add pricing calculator to the pricing page

### ISSUE THREAD

**Issue by advtszn** [zeropsio/docs#85]
### Preliminary Checks

- [X] I have searched for similar issues: https://github.com/zeropsio/docs/issues

### Issue Summary

Implementation of a pricing calculator similar to the one on fly.io and railway.app

### Suggested Solution

1.
2.
3.

### Would you like to help fix this issue?

- [X] I would like to work on this

**Comment by nermalcat69** [comment]
Thanks Astro!!
